# Generated by Django 4.2.7 on 2026-09-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['created_at'], name='work_created_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['author', '-created_at'], name='work_author_created_idx'),
        ),
    ]
